#!/bin/bash

export GOPATH="$HOME/code/go"
export NVM_DIR="$HOME/.nvm"
export MAGICK_HOME="$HOME/ImageMagick-7.0.8"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"
export TOOLS_HOME="$HOME/tools"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# PATH

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
fpath[1,0]="/opt/homebrew/share/zsh/site-functions";
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/caleb.gregory/Library/Application Support/JetBrains/Toolbox/scripts";

[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

export PATH="$PATH:$HOME/.local/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opts/bin:/usr/local/go/bin:$GOPATH:$GOPATH/bin:$MAGICK_HOME/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$HOME/Library/Application Support/JetBrains/Toolbox/scripts:$HOME/bin:$TOOLS_HOME/bin:$TOOLS_HOME/scripts"
