#!/bin/bash
#MISE description="get the pictures off of the SD card"

set -eou pipefail

sd_card_volume=''
for known in '/Volumes/sandisk1' '/Volumes/sandisk2'; do
  if [ -d "$known" ]; then
    sd_card_volume="$known"
  fi
done
if [ -z "$sd_card_volume" ]; then
  echo "sd_card not found!"
  exit 1
fi

staged_dir="$HOME/Pictures/_staged"

mkdir -p "$staged_dir"

rm -f "$staged_dir/.DS_Store"

if [ -n "$(ls -A "$staged_dir")" ]; then
  echo "WARNING: $staged_dir is not empty!"
fi

mv "$sd_card_volume"/DCIM/*_FUJI/* "$staged_dir"

file_count="$(find "$staged_dir" -type f | wc -l)"
total_size="$(du -sh "$staged_dir" | cut -f1)"
echo "moved $file_count files ($total_size)"

open "$staged_dir"

diskutil unmount "$sd_card_volume"
