#!/bin/bash
#MISE description="upload the pictures to immich"
#USAGE arg "<dir>"

set -eou pipefail

album_dir="$usage_dir"

if [ -z "$(ls -A "$album_dir")" ]; then
  echo "$album_dir is empty!"
  exit 1
fi

pnpm immich upload --album --ignore '**/*.MOV' --recursive "$album_dir"
